- name: pass_prepare
  scope:
    branch:
      - '*'
    dept:
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎部-事务
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎部-RS组
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎部-日志
  must_success:
    false
- name: weak_read
  scope:
    branch:
      - '*'
    dept:
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎部-事务
  must_success:
    false
- name: duplicate_table_access
  scope:
    branch:
      - '*'
    dept:
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎部-事务
  must_success:
    false
- name: PREPARE_STANDBY
  scope:
    branch:
      - '*'
    dept:
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎部-RS组
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎部-日志
  must_success:
    false
- name: direct_load
  scope:
    branch:
      - '*'
    dept:
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎部-存储-索引与DDL
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎部-存储-物化
  must_success:
    false
- name: ddlhome
  scope:
    branch:
      - '*'
    dept:
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎部-存储-索引与DDL
  must_success:
    false
- name: mv_home
  scope:
    branch:
      - '*'
    dept:
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎部-存储-物化
  must_success:
    false
- name: obtest
  scope:
    branch:
      - '*'
    dept:
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎部-存储-高可靠
  must_success:
    false
- name: obbstool_farm
  scope:
    branch:
      - '*'
    dept:
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎部-存储-高可靠
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎部-云存储
  must_success:
    false
- name: stress_json
  scope:
    branch:
      - '*'
    dept:
      - OceanBase-OceanBase-产品技术部-技术部-深圳研发中心
  must_success:
    false
- name: stress_xml_4.2
  scope:
    branch:
      - '*'
    dept:
      - OceanBase-OceanBase-产品技术部-技术部-深圳研发中心
  must_success:
    false
- name: PASS_SQL
  scope:
    branch:
      - '*'
    dept:
      - OceanBase-OceanBase-产品技术部-技术部-SQL-执行器
      - OceanBase-OceanBase-产品技术部-技术部-SQL-优化器
  must_success:
    false
- name: PASS_PL
  scope:
    branch:
      - '*'
    dept:
      - OceanBase-OceanBase-产品技术部-技术部-SQL-存储过程
  must_success:
    false
- name: VOS_PASS
  scope:
    branch:
      - '*'
    dept:
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎部-系统
  must_success:
    false
- name: PASS_DAS
  scope:
    branch:
      - '*'
    dept:
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎部-交互诊断
  must_success:
    false
- name: QA_DAS_REGRESSION
  scope:
    branch:
      - '*'
    dept:
      - OceanBase-OceanBase-产品技术部-技术部-底层引擎部-交互诊断
  must_success:
    false
